### ISSUE TITLE
Helm Chart should have no network dependecies

### ISSUE THREAD

**Issue by phisco** [cyberark/sidecar-injector#11]
Trying to install the helm chart in a strictly segregated environment where no access to the internet can be assumed, we noticed the helm chart is trying to create a deployment with an initContainer downloading kubectl at run time. 

It would be really nice if you could use an image that already has such a dependency and make the helm chart less dependent on network connectivity as possible.

I would open a PR, but I guess it would be better for you to own the image and therefore this repository could not be the right place for that, let me know if that's not the case and I'll be happy to contribute.

**Comment by hughsaunders** [comment]
Hi @phisco, thanks for reaching out :) 
So I can understand your situation, are you downloading images to a local registry, then deploying in an environment that has access to your local registry but not general internet access? 

If we pushed an image to dockerhub that contained both google cloud sdk and kubectl, you could cache that in your local registry, and the init container would work in your offline environment?

Reference: https://github.com/cyberark/sidecar-injector/blob/master/charts/cyberark-sidecar-injector/templates/deployment.yaml#L37

**Comment by phisco** [comment]
Hi @hughsaunders, thanks for your quick reply!
That's exactly my use case and yes an image on dockerhub would allow me to pull it to my local registry and use it.

**Comment by hughsaunders** [comment]
Great, we can't work on this right now but its a good idea for the future and we'll address it when we can.
