### ISSUE TITLE
Update API version in deployment.yaml

### ISSUE THREAD

**Issue by CaptainFluffyToes** [cyberark/sidecar-injector#21]
## Summary
The deploylment.yaml uses apiVersion: extensions/v1beta1 for the deployment declaration. This is deprecated on newer clusters and should be apps/v1. Also, you need to add in a selector to the deployment once you do change to apps/v1. 
## Steps to Reproduce
1. kubectl apply -f deployment.yaml
2. See error that 

## Expected Results
Deployment should successfully load. 

## Actual Results (including error logs, if applicable)
kubectl complains that there is no Type deployment in extensions/v1beta1

**Comment by doodlesbykumbi** [comment]
Resolved by https://github.com/cyberark/sidecar-injector/pull/27
