### ISSUE TITLE
Add ability to inject conjur-access-token volume mounts to a selection of containers

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/sidecar-injector#25]
Update the sidecar injector to enable injecting a volume mount to the `conjur-access-token` into the container definition of specified containers.

## Context
The sidecar injector when used to inject the authenticator will create the `conjur-access-token` volume and inject the authenticator sidecar. If you want your application container to create a mount to the `conjur-access-token` volume:
```
volumeMounts:
  - mountPath: /run/conjur
    name: conjur-access-token
```
 then you have to create a volume mount on that container to a volume that doesn't exist at the time you invoke `kubectl apply -f ..`. This can have mixed results depending on when validation of the pod spec takes place. 

A better approach is to introduce an annotation option to the sidecar-injector that allows the sidecar-injector to automatically add these volume mounts to containers whose names you specify. Perhaps `sidecar-injector.cyberark.com/conjurTokenReceivers`, which would take a comma separated list of container names.

**Comment by doodlesbykumbi** [comment]
Here's the suggestion for this will be implemented. There'll be a new configuration option identified by the annotation key `sidecar-injector.cyberark.com/conjurTokenReceivers`. It'll take a comma separated string value containing the list of containers that should get the conjur-access-token volume mount injected.

e.g. 
```
sidecar-injector.cyberark.com/conjurTokenReceivers: "app-container-1, app-container-2"
```

Re: Implementation, we will need to 
0. Retrieve and parse the annotation above to create a slice of the container names that will received the volume mounts.
1. Create a method for returning the required patch operations for adding volume mounts. This will be similar to the function for adding volumes  https://github.com/cyberark/sidecar-injector/blob/master/pkg/inject/patch.go#L56
2. Use (1) to only add the conjur-access-token volume mount to the containers.

**Comment by sgnn7** [comment]
> annotation key `sidecar-injector.cyberark.com/conjurTokenReceivers`

I'd propose something a bit less redundant and conforming to k8s ones:
`cyberark.com/conjur-token-receivers`

Other than that, from the cursory look the rest seems fine but I don't know enough about the injector nor the context here to be a reliable reviewer 🤷 .

**Comment by diverdane** [comment]
This proposal certainly looks reasonable to me.
For the purposes of brainstorming, how about this as an alternative. I'm not totally certain this would work, and it's probably no better than what you've proposed, but what the heck:

- Use a Kubernetes secret to pass the token instead of a volume
- For initial deployment, create an initial Kubernetes secret with a blank/null token (might need a validity flag in the data to indicate valid secret?)
- For containers that will need the token, include a volume mount to that secret
- When the sidecar is injected, update the token secret with the *actual* token via mutating admission webhook.
- Containers that volume mounted this secret will automatically see an updated token in their file systems after the secret update.

**Comment by doodlesbykumbi** [comment]
@diverdane The authenticator sidecar model has one authenticator per pod. Using a secret would mean as many secrets as there are pods (I think). The authenticator sidecar would need to be able to write to this secret. I'm also not sure how fast a change to a secret propagates to volume mount sin currently running containers (if at all).

If you were concerned about the security implications of using a volume it's worth noting that the volume that holds the access token is uses the in memory storage medium and is only shared between containers in the Pod.

**Comment by doodlesbykumbi** [comment]
@sgnn7 I hear ya, however the choice of name style has to be consistent with the other parameters.

**Comment by diverdane** [comment]
@doodlesbykumbi thanks for the clarifications, that makes sense! My intent with making this suggestion was possible simplification of the mutation process if possible (it wasn't for security concerns). It hadn't occurred to me that the authenticator sidecar would need to write this volume... but yeah, that makes total sense. This would be way too complicated for the sidecar to update a secret; that would require an integrated kubernetes client.

What you're proposing LGTM, thanks!

**Comment by sgnn7** [comment]
@doodlesbykumbi what are the other parameters that we're trying to stay consistent with?

**Comment by doodlesbykumbi** [comment]
All the parameters listed here https://github.com/cyberark/sidecar-injector/blob/master/README.md#configuration
