### ISSUE TITLE
Configurable sidecar container images

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/sidecar-injector#29]
At present the container images for the Authenticator, and Secretless sidecars are hardcoded to the latest versions available from Dockerhub. Users of the injector will likely want to customize this. 

This could be achieved in a variety of ways. This issue is to discuss them.

**Comment by doodlesbykumbi** [comment]
Some ideas:
1. Add an annotation for each container image. This means each container can override the sidecar container image by setting an annotation in the Pod template spec. This is completely dynamic and might have security implications since you can use this to inject an arbitrary container.

2. The sidecar-injector process can take static configuration on startup. This could be environment variables or flags, with defaults. These static values will set the container image values to be injected for the lifetime of the process. 

(1) and (2) only think about overriding the container image. It may well be that users of the injector require more control. For that we might take inspiration from Istio and,

3. Introduce the concept of an injection policy.  These injection policies would live in Kubernetes resources ConfigMap or CRDs. Istio alludes to the `istio-sidecar-injector ConfigMap` at https://istio.io/blog/2019/data-plane-setup/#automatic-injection. It's a config map that holds configuration values for injection and a template containing the resources to inject. This gives a lot of flexibility to users since they can tweak anything about the resources they want injected.

**Comment by doodlesbykumbi** [comment]
I would recommend (1) for the short term. (2) requires more consideration regarding security implications etc.  and (3) would require significant design and time investment.

---

For (1) the usage might look as follows:
```
cyberark-sidecar-injector \
  --secretless-container-image=path/to/secretless/container/image/repo/and/tag \
  --authenticator-container-image=path/to/authenticator/container/image/repo/and/tag
```
or
```
CONTAINER_IMAGE_SECRETLESS=path/to/secretless/container/image/repo/and/tag \ 
CONTAINER_IMAGE_AUTHENTICATOR=path/to/secretless/container/image/repo/and/tag \ 
 cyberark-sidecar-injector
```

**Comment by izgeri** [comment]
can you clarify where adding these image names would be set (maybe by linking to the README)?

this sounds good to me, but I would like to understand better how this will change the deployment / usage of the sidecar injector

I also am curious how the sidecar injector would behave if no image is specified - would this be implemented, for example, so that if no image is set for secretless and/or the authenticator, the default (`latest` from dockerhub) would be used instead? whatever the rule is, can we be sure to call that out in the documentation as part of this update?

thanks!!

**Comment by doodlesbykumbi** [comment]
Defaults will necessarily be the latest image on Dockerhub for both secretless and the authenticator. 

At present we give 2 methods of deployment. 
1. Run the script we provide in the repo
2. Use the helm chart

Both will need to accept the additional parameters for specifying the container images. 

For example instead of running step 3 in the manual deployment (see https://github.com/cyberark/sidecar-injector#deploy-sidecar-injector) the deployment manifest will be shell templated so that it becomes something like this:
```
./deployment/deployment.yaml.sh \
  --secretless-container-image=path/to/secretless/container/image/repo/and/tag \
  --authenticator-container-image=path/to/authenticator/container/image/repo/and/tag \
  > ./deployment/deployment.yaml

kubectl -n injectors apply -f ./deployment/deployment.yaml 
```

The values passed to the shell template script will be set on the sidecar-injector pod command args https://github.com/cyberark/sidecar-injector/blob/master/deployment/deployment.yaml#L21.

It's the same idea for the helm chart accept the helm chart takes "values".

**Comment by izgeri** [comment]
I think it's worth spelling that all out in this issue - doing so will also make writing the README updates for this a lot easier

So it sounds like both installation flows will need to be updated

## Installing manually

The instructions for [deploying the sidecar injector](https://github.com/cyberark/sidecar-injector#installing-the-sidecar-injector-manually) will have a new (optional?) step between steps (2) and (3) that is to "Update the sidecar injector deployment with specific Secretless and/or Conjur Authenticator Docker image references:

```
./deployment/deployment.yaml.sh \
  --secretless-container-image=path/to/secretless/container/image/repo/and/tag \
  --authenticator-container-image=path/to/authenticator/container/image/repo/and/tag \
  > ./deployment/deployment.yaml
```

## Installing using the helm chart

If you want to use the default `latest` Dockerhub images, you can run the usual command:
```
helm --namespace injectors \
 install \
 --set "caBundle=$(kubectl -n kube-system \
   get configmap \
   extension-apiserver-authentication \
   -o=jsonpath='{.data.client-ca-file}' \
 )" \
 ./charts/cyberark-sidecar-injector/
```

Optionally, if you want to specify the Secretless and/or Conjur Authenticator Docker image references, you can specify this in the `helm install` command:
```
helm --namespace injectors \
 install \
 --set "
    caBundle=$(kubectl -n kube-system \
      get configmap \
      extension-apiserver-authentication \
      -o=jsonpath='{.data.client-ca-file}' \
    ),
    secretless-container-image=path/to/secretless/container/image/repo/and/tag,
    authenticator-container-image=path/to/authenticator/container/image/repo/and/tag
  " \
 ./charts/cyberark-sidecar-injector/
```
(is this what you're thinking?)

## Updating an existing deployment

[needs more info]

**Comment by doodlesbykumbi** [comment]
Yup. This is what I was thinking.

**Comment by doodlesbykumbi** [comment]
Re: Updating an existing deployment:

```
# Set the secretless-image flag by appending to the command args of the sidecar injector container definition using a json patch
kubectl patch deployment valid-deployment  \
  --type json \
  -p='
[
  {
    "op": "add",
    "path": "/spec/containers/0/args",
    "value": "-secretless-image=path/to/secretless/container/image/repo/and/tag"
  }
]
'
```

**Comment by doodlesbykumbi** [comment]
Re: Updating an existing deployment:

It can be accomplished in a variety of ways. The goal is to set the flags `-secretless-image` and `-authenticator-image` as entries in the command args of the sidecar injector container definition.

Here's an example using a json patch for the `-secretless-image` flag:
```
# Set the secretless-image flag by appending to the command args of the sidecar injector container definition using a json patch
kubectl patch deployment valid-deployment  \
  --type json \
  -p='
[
  {
    "op": "add",
    "path": "/spec/containers/0/args",
    "value": "-secretless-image=path/to/secretless/container/image/repo/and/tag"
  }
]
'
```

**Comment by doodlesbykumbi** [comment]
Some inspiration https://engineering.salesforce.com/a-generic-sidecar-injector-for-kubernetes-c05eede1f6bb
