### ISSUE TITLE
There exists tagged releases for the sidecar-injector

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/sidecar-injector#32]
This is an important step towards towards having trusted releases. It also makes for a better UX for consumers of this. Using `latest` is always a risk.

- [ ] Docker image exists on Dockerhub with tagged image
- [ ] There's a release in the releases section of the repo
- [ ] Tag images using commit

**Comment by izgeri** [comment]
@doodlesbykumbi if this is done, can you update the checkmarks please?
