### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by CaptainFluffyToes** [cyberark/sidecar-injector#57]
## Summary
Running the manual steps for deployment. Generating the certificates results in this deprecation warnings: 

- Warning: certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
- W0222 23:19:50.734919   15383 helpers.go:553] --dry-run is deprecated and can be replaced with --dry-run=client.

## Steps to Reproduce

1. Execute certificate deployment script: ./deployment/webhook-create-signed-cert.sh     --service cyberark-sidecar-injector     --secret cyberark-sidecar-injector     --namespace injectors

## Expected Results
No warnings

## Actual Results (including error logs, if applicable)
Warnings for deprecation of the API for certificates and for using dry run. 

## Reproducible
   * [x ] Always 

   
## Version/Tag number
Latest Master branch. 

## Environment setup
Openshift 4.16
Azure

**Comment by CaptainFluffyToes** [comment]
Openshift version 4.6 not 4.16

**Comment by doodlesbykumbi** [comment]
The scripts don't use `--dry-run` so I don't think we have to do anything for that deprecation warning. I think it's pretty cool that they now have the option for client and server dry runs.

For the CertificateSigningRequest, and other API versions in the manifests I think we should dynamically determine those. For example, to find the latest supported version of CertificateSigningRequest on your cluster run 
```
kubectl explain CertificateSigningRequest | grep "VERSION:" | head -1 | awk '{print $2}'
```
